### ISSUE TITLE
React style guide: naming Props interface

### ISSUE THREAD

**Issue by dricholm** [zehitomo/eslint-config#1]
Currently we use `interface Props {}` as the props type in a component and don't export it. I would like to export some prop types for easier Storybook setup and could also come in handy in some cases. What should be the recommended way for this?

1. Rename the `Props` to `${ComponentName}Props` (e.g. `Button.tsx` would use `ButtonProps`) and use `export interface ButtonProps {}`.
1. Leave the name as it is (`Props`) and use `export { Props as ButtonProps }` below the default export.

Last time I refactored `z-web\src\modules\layout\components\MenuItem.tsx` I chose option 1 and the Props are used in `Menu.desktop.tsx` and `Menu.phone.tsx` now. However I feel both are good options and choosing option 2 would result in the least amount of changes.

**Comment by a-ogilvie** [comment]
@dricholm I have a slight preference for option 2, but I think both approaches are reasonable.
