### ISSUE TITLE
TypeScript sort keys

### ISSUE THREAD

**Issue by dricholm** [zehitomo/eslint-config#5]
Since `sort-keys` is used in JavaScript files, how about introducing [eslint-plugin-typescript-sort-keys](https://github.com/infctr/eslint-plugin-typescript-sort-keys)?
This can check for key order in interfaces and string enums.
We currently don't enforce this with a linter, but I remember seeing some comments regarding this in reviews. This would help to catch them before commit.

**Comment by mattcarpenter** [comment]
I support this – It's useful in preventing merge conflicts.

**Comment by a-ogilvie** [comment]
I support this too.

Since this is a TS plugin, we'll need to add it at the `z-web` and `z-web-angular` level (as opposed to making a change in this repo).

**Comment by dricholm** [comment]
> Since this is a TS plugin, we'll need to add it at the `z-web` and `z-web-angular` level (as opposed to making a change in this repo).

@a-ogilvie The rules should be added to this repo though as with other TS/React rules, right?
Of course installing the dependency should only be done on the repos that use it.

**Comment by a-ogilvie** [comment]
> > Since this is a TS plugin, we'll need to add it at the `z-web` and `z-web-angular` level (as opposed to making a change in this repo).
> 
> @a-ogilvie The rules should be added to this repo though as with other TS/React rules, right?
> Of course installing the dependency should only be done on the repos that use it.

@dricholm You're right! I'd forgotten that we (I 🤦‍♂️) separated the rules into this package.

So far, we've created a new file per plugin. I think we should create a new file `typescript-sort-keys.js` and add rules there.

Be sure to use the same ruleset as the existing `sort-keys` rule.

```js
{  
  'sort-keys': ['warn', 'asc', { natural: true }],
}
```
